name: Release app

on:
  workflow_dispatch:

# Add permissions block at the top level
permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os:
          [
            { name: 'linux', image: 'ubuntu-latest' },
            { name: 'windows', image: 'windows-latest' },
            { name: 'macos-universal', image: 'macos-latest', arch: 'universal' },
          ]

    runs-on: ${{ matrix.os.image }}

    steps:
      - name: Github checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - name: Publish app
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          APPLE_ARCH: ${{ matrix.os.arch }}
        run: npm run publish 

      - name: Update GitHub Release notes for macOS quarantine
        if: runner.os == 'Linux'
        uses: IsaacShelton/update-existing-release@v1.3.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # If you know the tag, specify it below:
          tag: ${{ github.ref_name }} # or use the actual release tag
          # Optionally, set release: ${{ github.event.release.name }}
          body: |
            ## macOS quarantine:
            This app is not signed, so you might get a warning when you try to open it. 
            There are two possible workarounds:
      
            - You can either override the security settings by following [the instructions here](https://support.apple.com/en-gb/guide/mac-help/mh40617/15.0/mac/15.0).
            - If you are not able to do that, you can remove the quarantine attribute by running the following command in the terminal:
      
            ```
            # Replace /path/to/WP\ Shell.app with the actual path to your downloaded app
            sudo xattr -d com.apple.quarantine /path/to/WP\ Shell.app
            ```
